/**
 * The bot reference lap for each course: what the machine pilot managed.
 *
 * Times and splits only — a few hundred bytes, so they ship with the page. The
 * *video* of each lap does not: it is fetched from `/reference/` when a pilot
 * presses play, because the page is 170 KB and a bundled video per course would
 * be two orders of magnitude more for something most visitors never watch.
 *
 * Generated by `npm run reference`, which optimises a line, flies it with
 * `Autopilot`, and writes this file. Regenerate it when a course changes or the
 * flight model does — the numbers are only meaningful against the model that
 * produced them, which is why `build` and `generated` are recorded here rather
 * than left to memory.
 *
 * It is a *reference*, not a limit. It is the best a short search found under
 * this model, flown by a machine with perfect knowledge of its own state and no
 * reaction time. A pilot beating it is interesting rather than impossible.
 */

export interface ReferenceLap {
  /** The course this belongs to, by name — the same name the map carries. */
  course: string;
  /** Best lap the reference achieved, seconds. */
  lap: number;
  /** Time to the first checkpoint from a standing start. */
  holeShot: number;
  /** Gate-to-gate deltas of that lap, in checkpoint order. */
  splits: number[];
  /** Top speed reached, m/s. */
  topSpeed: number;
  /** File under /reference/, or null when no video has been produced. */
  video: string | null;
  /** Which build flew it, and when. */
  build: string;
  generated: string;
}

import data from './reference-data.json';

/**
 * Written by `node tools/write-reference.mjs`, which is why it is JSON rather
 * than hand-edited TypeScript: a generated file that looks like source invites
 * someone to edit it, and the next regeneration would silently throw that away.
 */
export const REFERENCE_LAPS: ReferenceLap[] = data as ReferenceLap[];

export function referenceFor(courseName: string): ReferenceLap | null {
  return REFERENCE_LAPS.find((r) => r.course === courseName) ?? null;
}
